Murray_Final/Murray_P1/Murray_P1/Controllers/JordanCustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Murray_P1.Models;

namespace Murray_P1.Controllers
{
    public class JordanCustomersController : Controller
    {
        // GET: JordanCustomers
        public ActionResult Index()
        {
            return View();
        }

        // GET:  /JordanCustomers/ByState/NC
        public ActionResult ByState(string id)
        {
            JordanDBEntities db = new JordanDBEntities();

            List<ShopCustomer> customers = new List<ShopCustomer>();

            customers = db.ShopCustomers.ToList();

            var sortedList = customers.Where(m => m.CustomerState == id)
                                        .OrderBy(m => m.CustomerFirstName);

            ViewBag.ChosenState = id;

            return View(sortedList);
        }

        //GET:  /JordanCustomers/Details/APetitt@gmail.com
        public ActionResult Details(string id)
        {
            JordanDBEntities db = new JordanDBEntities();

            List<ShopCustomer> customers = new List<ShopCustomer>();

            customers = db.ShopCustomers.ToList();

            var foundCustomer = customers.Where(m => m.CustomerFirstName == id)
                                        .First();

            return View(foundCustomer);
        }
    }
}

Murray_Final/Murray_P1/Murray_P1/Controllers/JordanStatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Murray_P1.Models;

namespace Murray_P1.Controllers
{
    public class JordanStatesController : Controller
    {
        //Declare a class-level List Collection of JordanStates objects
        List<PossibleState> states = new List<PossibleState>();

        //Class Constructor method
        public JordanStatesController()
        {
            JordanDBEntities db = new JordanDBEntities();

            states = db.PossibleStates.ToList();
        }

        // GET: JordanStates
        public ActionResult Index()
        {

            return View();
        }

        // GET: JordanStates/ChooseState
        public ActionResult ChooseState()
        {
            //JordanDBEntities db = new JordanDBEntities();

            //List<PossibleState> customers = new List<PossibleState>();

            //customers = db.PossibleStates.ToList();

            var sortedList = states
                                .OrderBy(m => m.FullStateName)
                                .ToList();

            return View(sortedList);
        }
    }
}

Murray_Final/Murray_P1/Murray_P1/Views/JordanCustomers/ByState.cshtml
@model IEnumerable<Murray_P1.Models.ShopCustomer>

@{
    ViewBag.Title = "ByState";
}

<h2>State: @ViewBag.ChosenState</h2>


<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerLastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href='@Url.Action("Details", "JordanCustomers", new { id = item.CustomerFirstName })'>

                    @Html.DisplayFor(modelItem => item.CustomerFirstName)
                    </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerEmail)
            </td>
        </tr>
    }
    <tr>
        <td colspan="5" class="text-center">
            @Html.ActionLink("Back", "ChooseState", "JordanStates")
        </td>

</table>

Murray_Final/Murray_P1/Murray_P1/Views/JordanCustomers/Details.cshtml
@model Murray_P1.Models.ShopCustomer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ShopCustomer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerPhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerPhoneNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerEmail }) |
    @Html.ActionLink("Back to States", "ChooseState", "JordanStates")
</p>