Murray_Final/Murray_P1/Murray_P1/Models/JordanInventory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Murray_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JordanInventory
    {
        public string ItemStyleNum { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string ProductCategoryCode { get; set; }
        public string ImageFile { get; set; }
    }
}

Murray_Final/Murray_P1/Murray_P1/Controllers/JordanCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Murray_P1.Models;

namespace Murray_P1.Controllers
{
    public class JordanCategoriesController : Controller
    {
        //Declare a class-level List Collection of JordanCategory objects
        List<ProductCategory> categories = new List<ProductCategory>();

        //Class Constructor method
        public JordanCategoriesController()
        {
            JordanDBEntities db = new JordanDBEntities();

            categories = db.ProductCategories.ToList();
        }

        // GET: JordanCategories
        public ActionResult Index()
        {

            return View();
        }

        // GET: JordanCategories/ChooseCategory
        public ActionResult ChooseCategory()
        {
            //JordanDBEntities db = new JordanDBEntities();

            //List<ProductCategory> categories = new List<ProductCategory>();

            //categories = db.ProductCategories.ToList();

            var sortedList = categories
                                .OrderBy(m => m.CategoryName)
                                .ToList();

            return View(sortedList);
        }
    }
}

Murray_Final/Murray_P1/Murray_P1/Controllers/JordanInventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Murray_P1.Models;

namespace Murray_P1.Controllers
{
    public class JordanInventoryController : Controller
    {
        // GET: JordanInventory
        public ActionResult Index()
        {
            return View();
        }

        // GET:  /JordanInventory/ByCategory/Shoes
        public ActionResult ByCategory(string id)
        {
            JordanDBEntities db = new JordanDBEntities();

            List<JordanInventory> inventory = new List<JordanInventory>();

            inventory = db.JordanInventories.ToList();

            var sortedList = inventory.Where(m => m.ProductCategoryCode == id)
                                        .OrderBy(m => m.ProductName);

            ViewBag.ChosenCategoryCode = id;

            return View(sortedList);
        }

        //GET:  /JordanInventory/Details/546480-012
        public ActionResult Details(string id)
        {
            JordanDBEntities db = new JordanDBEntities();

            List<JordanInventory> inventory = new List<JordanInventory>();

            inventory = db.JordanInventories.ToList();

            var foundProduct = inventory.Where(m => m.ItemStyleNum == id)
                                        .First();

            return View(foundProduct);
        }
    }
}

Murray_Final/Murray_P1/Murray_P1/Views/JordanInventory/ByCategory.cshtml
@model IEnumerable<Murray_P1.Models.JordanInventory>

@{
    ViewBag.Title = "ByCategory";
}

<h2>Category: @ViewBag.ChosenCategoryCode</h2>


<table class="table table-bordered table-striped">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemStyleNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductCategoryCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href='@Url.Action("Details", "JordanInventory", new { id = item.ItemStyleNum })'>

                    <img src="@Url.Content("~/Images_Products/" + item.ImageFile)" height="100" width="100">

                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemStyleNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductCategoryCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductPrice)
            </td>
        </tr>
    }
    <tr>
        <td colspan="5" class="text-center">
            @Html.ActionLink("Back", "ChooseCategory", "JordanCategories")
        </td>

</table>

Murray_Final/Murray_P1/Murray_P1/Views/JordanInventory/Details.cshtml
@model Murray_P1.Models.JordanInventory

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>JordanInventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemStyleNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemStyleNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductCategoryCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductCategoryCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageFile)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemStyleNum }) |
    @Html.ActionLink("Back to Categories", "ChooseCategory", "JordanCategories")
</p>