Murray_Final/Murray_P1/Murray_P1/Controllers/JordanCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Murray_P1.Models;

namespace Murray_P1.Controllers
{
    public class JordanCategoriesController : Controller
    {
        //Declare a class-level List Collection of JordanCategory objects
        List<ProductCategory> categories = new List<ProductCategory>();

        //Class Constructor method
        public JordanCategoriesController()
        {
            JordanDBEntities db = new JordanDBEntities();

            categories = db.ProductCategories.ToList();
        }

        // GET: JordanCategories
        public ActionResult Index()
        {

            return View();
        }

        // GET: JordanCategories/ChooseCategory
        public ActionResult ChooseCategory()
        {
            //JordanDBEntities db = new JordanDBEntities();

            //List<ProductCategory> categories = new List<ProductCategory>();

            //categories = db.ProductCategories.ToList();

            var sortedList = categories
                                .OrderBy(m => m.CategoryName)
                                .ToList();

            return View(sortedList);
        }
    }
}

Murray_Final/Murray_P1/Murray_P1/Controllers/JordanStatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Murray_P1.Models;

namespace Murray_P1.Controllers
{
    public class JordanStatesController : Controller
    {
        //Declare a class-level List Collection of JordanStates objects
        List<PossibleState> states = new List<PossibleState>();

        //Class Constructor method
        public JordanStatesController()
        {
            JordanDBEntities db = new JordanDBEntities();

            states = db.PossibleStates.ToList();
        }

        // GET: JordanStates
        public ActionResult Index()
        {

            return View();
        }

        // GET: JordanStates/ChooseState
        public ActionResult ChooseState()
        {
            //JordanDBEntities db = new JordanDBEntities();

            //List<PossibleState> customers = new List<PossibleState>();

            //customers = db.PossibleStates.ToList();

            var sortedList = states
                                .OrderBy(m => m.FullStateName)
                                .ToList();

            return View(sortedList);
        }
    }
}

Murray_Final/Murray_P1/Murray_P1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Murray_P1</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body align="center">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Project 1", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Products", "ChooseCategory", "JordanCategories")</li>
                    <li>@Html.ActionLink("Customers", "ChooseState", "JordanStates")</li>
                </ul>
            </div>
        </div>
    </div>
    <div align="center" class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cyborg Theme</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>